name: 'Chromatic'

on:
    pull_request:
        branches:
            - main

jobs:
    chromatic-deployment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Install dependencies
              run: yarn install
            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                  # 👇 Chromatic projectToken, refer to the manage page to obtain it.
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
